; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Feb 02 2020 20:26:37 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

